export const ROUTE_CONSTANTS = {
  SLASH: "/",
  UNAUTHORIZED: "/unauthorized",
  LOGIN: "/auth/login",
  DASHBOARD: "dashboard",
  PRODUCTS: "products",
  HISTORY: "history",
  CASH_CHECKER: "cash-checker",
  DAILY_LEDGER: "daily-ledger",
  MONTHLY_REPORTS: "monthly-reports",
  NOTIFICATION: "notification",
  PAYMENTS: "payments",
  PURCHASE_ORDER: "purchase-order",
  SETTINGS: "settings",
  SUPPORT: "support",
  ADD_PURCHASE_ORDER: "add-purchase-order",
  ADMIN_DASHBOARD: "admin-dashboard",
  RECENT_INVOICES: "recent-invoices",
};
