export const ROUTE_CONSTANTS = {
  SLASH: "/",
  UNAUTHORIZED: "/unauthorized",
  LOGIN: "/auth/login",
  DASHBOARD: "dashboard",
  PRODUCTS: "products",
  // HISTORY: "history",
  CUSTOMER: "customers",
  VIEW_CUSTOMERS: "view-customer",
  VIEW_ALL_INVOICES: "view-all-invoices",
  CASH_CHECKER: "cash-checker",
  // DAILY_LEDGER: "daily-ledger",
  ACCESS_CONTROL: "access-control",
  ADD_EMPLOYEEE: "add-employee",
  EDIT_ACCESS: "edit-access",
  REPORTS: "reports",
  VIEW_MONTHLY_REPORTS: "view-monthly-reports",
  ACOUNT_RECEIVEABLE: 'acount-receiveable',
  VIEW_ACOUNT_RECEIVEABLE: 'view-acount-receiveable',
  ACOUNT_PAYABLE: 'acount-payable',
  MONTHLY_REPORT: 'monthly-report',
  NOTIFICATION: "notification",
  ORDERS: "orders",
  CREATE_ORDER: "create-orders",
  VIEW_ORDERS: "view-orders",
  CONVERT_TO_INVOICE: "convert-to-invoice",
  PURCHASE_ORDER: "purchase-order",
  // SETTINGS: "settings",
  EXPENSES: "expenses",
  ALL_EXPENSES: "all-expenses",
  ADD_EXPENSE: "add-expense",

  SUPPORT: "support",
  ADD_PURCHASE_ORDER: "add-purchase-order",
  RECENT_INVOICES: "recent-invoices",
};

// admin's pages
export const ADMIN_ROUTES = {
  ADMIN_DASHBOARD: "admin/dashboard",
  ADD_SUBSCRIPTION: "admin/add-subscription",
  SUBSCRIPTIONS_LIST: "admin/subscriptions-list",
  VIEW_SUBSCRIPTION: "admin/subscriptions-list/view-subscription",
};
