import Laptop1 from '../../images/Laptop1.png'

const Dummy_Add_PO = [
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    }
    ,
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    },
    {
        "Product Name":"Amazon Book",
        "description":"Amazing to read...",
        "threshold":"15 days",
        "IMEI Number":"123456789876543",
        "Serial Number":"12",
        "Category":"Books",
        "Sub category":"Amazonic",
        "Price":"$ 1222",
        "Color":"grey",
        "Size":"13.4 pt",
        "Quantity": "2x"
    }
]

export default Dummy_Add_PO