export const purchaseOrders = [
  {
    key: 1,
    poNumber: "63535",
    vendor: "lenovo",
    products: [
      { key: 1, name: "laptop", quantity: 12 },
      { key: 2, name: "iPhone", quantity: 20 },
      { key: 3, name: "airpods series", quantity: 60 },
      { key: 4, name: "headphone", quantity: 22 },
      { key: 5, name: "ipads", quantity: 32 },
    ],
    invoiceStatus: "pending",
    amount: 665.0,
    dueDate: "Friday 20 Jan 2023 12 AM EST",
    totalAmount: 778.0,
  },
  {
    key: 2,
    poNumber: "23535",
    vendor: "hp",
    products: [
      { key: 1, name: "laptop", quantity: 12 },
      { key: 2, name: "iPhone", quantity: 20 },
      { key: 3, name: "airpods series", quantity: 60 },
      { key: 4, name: "headphone", quantity: 22 },
      { key: 5, name: "ipads", quantity: 32 },
    ],
    invoiceStatus: "pending",
    amount: 665.0,
    dueDate: "Friday 20 Jan 2023 12 AM EST",
    totalAmount: 778.0,
  },
  {
    key: 3,
    poNumber: "63505",
    vendor: "Apple",
    products: [
      { key: 1, name: "laptop", quantity: 12 },
      { key: 2, name: "iPhone", quantity: 20 },
      { key: 3, name: "airpods series", quantity: 60 },
      { key: 4, name: "headphone", quantity: 22 },
      { key: 5, name: "ipads", quantity: 32 },
    ],
    invoiceStatus: "pending",
    amount: 665.0,
    dueDate: "Friday 20 Jan 2023 12 AM EST",
    totalAmount: 778.0,
  },
  {
    key: 4,
    poNumber: "83535",
    vendor: "lenovo",
    products: [
      { key: 1, name: "laptop", quantity: 12 },
      { key: 2, name: "iPhone", quantity: 20 },
      { key: 3, name: "airpods series", quantity: 60 },
      { key: 4, name: "headphone", quantity: 22 },
      { key: 5, name: "ipads", quantity: 32 },
    ],
    invoiceStatus: "pending",
    amount: 665.0,
    dueDate: "Friday 20 Jan 2023 12 AM EST",
    totalAmount: 778.0,
  },
];
